<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="PJI.DeliveryEventService.SecretsManager.Tests" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AWSSDK.SecretsManager" />
		<PackageReference Include="AWSSDK.SecurityToken" />
		<PackageReference Include="AWSSDK.SSO" />
		<PackageReference Include="AWSSDK.SSOOIDC" />
		<PackageReference Include="Microsoft.Extensions.Configuration" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Options" />
		<PackageReference Include="System.Threading.Tasks.Dataflow" PrivateAssets="none" />
	</ItemGroup>

</Project>
